
spring:
  datasource:
    username: root
    password: 8463ghhh
    url: jdbc:mysql://localhost:3306/gestionecole
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port : 587
    username: ecolegestion1@gmail.com
    password: zhvzpkswgkikzumg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



salesforce:
  token_url: https://login.salesforce.com/services/oauth2/token
  username: gecole@salesforce.com
  password: gestionecole2023XbjQ5yyKviToEErjgwsFFAsN
  client_id: 3MVG9DREgiBqN9WnS4v2pFmsgEt4t7xmLioRUoZnmm_znnvsundmnuwKb_H2gNAbQHnER5YWsGxMnhYh2WXa1
  client_secret: 8FCE550DEF1E4E3BC9422FA9598C13A6F69B9780F5B2D889F1BA41EA0A538DFB
  redirect_uri : https://login.salesforce.com/services/oauth2/success